from itertools import count
file=open("log.txt")
txt=file.read()
count_numErr = txt.count("DataErr")
count_noErr = txt.count("NoErr")
count_PDU = txt.count("PDU")
count_ok = txt.count("OK")
count_receive = txt.count("Receive")
file.close()
print("--------------")
print("PDU_num = %d"%count_PDU)
print("LOST_num= %d"%count_ok)
print("DataError_num = %d"%count_numErr)
print("OK_num = %d"%count_noErr)
print("Lost possibility = %.2f"%(count_ok / count_PDU))
print("Error possibility = %.4f"%(count_numErr / count_PDU))
print("--------------")
